services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: campus_bites
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/campus_bites_orders.csv:/docker-entrypoint-initdb.d/campus_bites_orders.csv

volumes:
  postgres_data:
